name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag docker-image:${{ github.sha }}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: |
        docker tag docker-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/docker-image:${{ github.sha }}
        docker tag docker-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/docker-image:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-image:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-image:latest
        
    - name: Run Docker Container
      run: |
        docker run -dit -p 8080:80 docker-image::latest   

    - name: Docker image
      run: |
        docker images
