name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag docker-latestimage:$(date +%s)
        #docker images
        #docker run -dit -p 80:80 
    - name: Check the Docker images
      run: docker images
    - name: Login to Docker
      run: docker login -e udaykumarreddy995@gmail.com -u udaykumarreddy995 -p 2235yYmGroqZ!
