name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: democontainerregistry7.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag democontainerregistry7.azurecr.io/docker-image:${{ github.sha }}
        docker push democontainerregistry7.azurecr.io/docker-image:${{ github.sha }}

    - name: Docker images
      run: |
        docker images 

    #- name: Tag Docker image
    #  run: |
    #    docker tag docker-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/docker-image:${{ github.sha }}
    #    docker tag docker-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/docker-image:latest

  #  - name: Push Docker image
  #    run: |
  #      docker push ${{ secrets.DOCKER_USERNAME }}/docker-image:${{ github.sha }}
  #      docker push ${{ secrets.DOCKER_USERNAME }}/docker-image:latest
        
  #  - name: Run Docker Container
  #    run: |
  #      docker run -dit -p 8080:80 docker-image:${{ github.sha }}

   # - name: Test the container
   #   run: |
   #     curl -I http://localhost:8080
